# Generated by Django 4.0.3 on 2022-05-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='deskription',
            new_name='description',
        ),
    ]
